### ISSUE TITLE
authenticate is calling next even if authentication fails

### ISSUE THREAD

**Issue by onur** [oauthjs/express-oauth-server#14]
Hi. I have a simple route:

```js
app.get('/secret_area', oauth.authenticate(), function(req, res) {
    res.send('OK');
});
```

oauth.authenticate() is always calling next and trying to send 'OK'. I am also getting: `Error: Can't set headers after they are sent.` when someone sends a invalid bearer token. I believe this is not how it suppose to work.

**Comment by onur** [comment]
Ahh this is duplication of #2 and I believe this is expected behavior.

**Comment by julienboulay** [comment]
I don't think it is the expected behavior. If the bearer token is invalid, it should send 40x error to the client and never execute the next step in the router.
There are also some inconsistencies, in the error handling and the response management

`res.send({ error: e.name, error_description: e.message });
  res.status(e.code);`
These lines will send an response before setting the status. So an http 200 will be send, even if an error occured.
The following line will fix it :
`res.status(e.code).send({ error: e.name, error_description: e.message });`
