### ISSUE TITLE
malformed authorization header

### ISSUE THREAD

**Issue by renanbastos93** [oauthjs/express-oauth-server#55]
PLEASE! Help-me...

> {
>     "error": "invalid_request",
>     "error_description": "Invalid request: malformed authorization header"
> }

not authentication, information down.

HEADER:
![image](https://user-images.githubusercontent.com/8202898/28886902-81117f24-7791-11e7-88e6-4c625507bd0b.png)

BODY:

![image](https://user-images.githubusercontent.com/8202898/28886908-89ab20b8-7791-11e7-85ac-44a6d9cc4cc8.png)

MONGO:

![image](https://user-images.githubusercontent.com/8202898/28886922-95cd14c8-7791-11e7-9074-ee762083952c.png)

**Comment by steffansluis** [comment]
You're Authorization header only has a client secret, no client id. You should send `'Basic' + new Buffer(client_id + ':' + 'client_secret).toString('base64')`.

**Comment by steffansluis** [comment]
Also, you seem to be trying to do a password grant with a client_credentials grant type.

**Comment by renanbastos93** [comment]
@steffansluis  hey man, I tried any forms, but not possible. You to know other form for me to achieve.

**Comment by steffansluis** [comment]
Truth be told, I haven't used this package in quite a while. I ended up implementing my own handlers using [node-oauth2-server](https://github.com/oauthjs/node-oauth2-server) because I needed some custom logic. You're probably best off reading through the code and debugging as you encounter different errors.

The error you are encountering is thrown [here](https://github.com/oauthjs/node-oauth2-server/blob/77c8e32ca1a145c10c40a5d0bdfb1a41130a186e/lib/handlers/authenticate-handler.js#L146) because it expects an access token in the Authorization header as opposed to client credentials. This comes from the [`handle` function on the authenticate handler](https://github.com/oauthjs/node-oauth2-server/blob/77c8e32ca1a145c10c40a5d0bdfb1a41130a186e/lib/handlers/authenticate-handler.js#L68). You seem to be wanting the [`token` handler](https://github.com/oauthjs/node-oauth2-server/blob/77c8e32ca1a145c10c40a5d0bdfb1a41130a186e/lib/handlers/token-handler.js#L93). The authenticate handler is supposed to validate requests, whereas the token handler actually handles the generation of tokens and such.

**Comment by renanbastos93** [comment]
Okay, I Understand, but with node-oauth2-server not accept request's with JSON it accept only request application/x-www-form-urlencoded I necessary using request with JSON, because of the frameworks that using in my front-end, what you advice?

**Comment by steffansluis** [comment]
Using node-oauth2-server (or this package for that matter) doesn't affect the rest of your API, only the authentication flow might require a particular encoding but if you really want you could get around that (not sure if the OAuth2 RFC allows for that though). Once you have requested a token you can simply create your own endpoint that authenticates first and then serves some JSON. It would look something like this:
```javascript
...

server.get('/myendpoint', OAuthServer.authenticate, (req, res) => {
  // Send any type of response here
  res.json({ hello: 'world' });
});

...
```

**Comment by renanbastos93** [comment]
@steffansluis  thanks, I will read better about the OAuth2 RFC, for me understand the specifications.
